# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night-eighties # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
theme: jekyll-text-theme
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : 장고(Django) 핥짝 맛보기
description: > # this means to ignore newlines until "Language & timezone"
  튜토리얼로 맛보는 장고(Django)의 맛. 떠먹여주진 않지만 떠먹을 수 있는 방법을 알려드립니다. 다양한 삽질의 과정을 통해서 삽질 잘 하는 방법을 터득하실 수 있습니다. 삽질 또한 때로는 테크닉이 될 수 있다는 마음으로 따라하신다면 훌륭한 삽질 전문가가 되실 겁니다. 시간이 충분하다면 맛보기에서 끝나지 않고 장고(Django) 내부구조까지 탈탈 털어내보겠습니다. 아니...터는 방법을 알려드리겠습니다.


## => Language and Timezone
##############################
lang: ko # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: Asia/Seoul # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : person # "person" (default), "organization"
  name      : Sehun Kim
  url       :
  avatar    : # path or url of avatar image
  bio       : Super Hero
  email     : paul-kim00@hanmail.net
  facebook  : swarf00 # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name/
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name/
  github    : https://github.com/swarf00 # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: swarf00/swarf00.github.com
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: gitalk # false (default), "disqus", "gitalk", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    enable: true
    clientID    : 61f2f8405228d0904e46 # GitHub Application Client ID
    clientSecret: 54f964dc521aaeb2e33a4fcde4a4aa1f526973df # GitHub Application Client Secret
    repository  : swarf00.github.io # GitHub repo
    owner       : swarf00 # GitHub repo owner
    admin: [swarf00] # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id


## => Pageview
##############################
pageview:
  provider: leancloud # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : YVRMlnD4JfgX9amFNdenzoXw-gzGzoHsz # LeanCloud App id
    app_key   : oS4RvCt8gKa5FuPtdAIDQhO3 # LeanCloud App key
    app_class : 0x0CKT7du6V2ze892kn9S3qj # LeanCloud App class


## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tag_manager:
      container_id: GTM-PN94PQT
    # tracking_id : # Google Analytics id for the site
    # anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
